import React from 'react'
import styles from "./Signature.module.css";
import CountUpOnView from './counter/Counter';

const Signature = () => {
  return (
    <section className={styles.section}>
        <div className={styles.container}>
            <CountUpOnView from={300} to={512} duration={2} />
            <span className={styles.signatureandcounting}>Signatories and counting in</span><span className={styles.tag}>D! UK</span>
        </div>
        <div className={styles.wordGrid}>
            {[
                '21–87', '216 Signs', '31% Wool', '400', 'A–Side.', 'Aalia Ahamed', 'Abbie Williams', 'ACRE – A Creative Endeavour Ltd', 'Active Matter', 'ACX', 'Adele Kelly', 'AdesignStorie', 'Advocate Design Agency', 'Aetha Design', 'Aileron Design Ltd', 'Alan Pitchforth', 'Alex Kimber Design', 'Alexander Miller', 'Alexandra Lunn Studio', 'Alexandra Lunn Studio', 'Alexie Sommer', 'Alexis Bardini', 'Ali Adair', 'Andrew Carr', 'ANdy Parker', 'Andy Thornton', 'Anja Klüver', 'Annabelle Vuille', 'Apfel', 'Applied Works', 'Archetype Accessories', 'Arif Yusop', 'Arrival', 'Avery & Brown', 'BA (Hons) Design for Sustainable Futures at Arts University Bournemouth', 'BA Graphic Design at Kingston School of Art', 'Badfish Labs', 'Baines Design LTD', 'Barbara Chandler', 'Barbara Chandler', 'Barry Bloye', 'Batch.Works', 'Baxter & Bailey', 'Be The Future', 'Beco', 'Beehive Green', 'Ben Clarke', 'Ben Jessop', 'Bencium Limited', 'Benedict Povey', 'Beta Design Office', 'BIB Design', 'big fish', 'Big Motive', 'Bill Searle', 'Biomimicry Innovation Lab', 'Bliss', 'Blunt Crayon', 'Bold Studio', 'Boyle & Perks', 'Brand Narrative at Pentagram', 'Bravand', 'Breezign', 'Bright Signals Design at Bright Signals Ltd.', 'Broadley Creative Ltd', 'Bronwen Rees', 'Buff Motion', 'Butterfly', 'BuyDesign', 'Carter Studio', 'Célibataire', 'Charli Blighton', 'Charli Peake', 'Charlotte Eagle', 'Charlotte Evans', 'Cherry Anderson Freelance Design', 'Chloe Poulter', 'Claire O’Neill', 'Claire Potter Design', 'Clara Greo', 'Clare Lewis', 'Claudiu', 'Clever Ghost', 'Climate Labs', 'Clive Russell', 'COHDA Design', 'Companion Studio', 'Conscious Hospitality Ltd', 'Conscious Sourcing', 'Contour', 'Creative at Delarki', 'Creative Concern', 'creative conscience', 'Creative Joy', 'Creative Joy', 'Creative Wilderness LTD', 'Curious Agency', 'Curious Agency', 'Curious Brand', 'CyDen Ltd',
                "Curious Agency","Curious Agency","Curious Brand","CyDen Ltd","D Squared Product Development Ltd","Daedalus","Daryl Wilkinson","Dave Cartledge","Dave Cuvelot","David Fairbrother","David Sudlow Designers","DEFY Brands","Design Activists for Regenerative Futures","Design Burger","Design by Country Ltd","Design by Mondial","Design Council","Design For Good Club","Design for Joy","Design Nature CIC","Design Science","Design Truth","DesignWright","DH Design Studios Ltd","Dids Macdonald","Dionne Griffith","Diploma in Professional Studies at London College of Communication","DISOMT","Dominik Bini","Dr Emma Powell","Dr Karl Jeffries","Drew Kendrick","Driftime® Media","Dylan Wiener","ecologicstudio","Edmuuund","Electro Strategy","Element Studio","Eleven","elise","Ella Porter","Elle Nelson Design","Ellie Burroughs","Emily Gorham","EMMA BRITTAIN","Emma Summerscales","emmabakerstudio","Eniola Ogunsola","Ensemble","Enviral","Etch","Ettive Design","Europa","Eva Koehle","Everything","Everywhere Design","Exeter Waste","F VENZANO","Fairground Studio","Farrah & Pearce Ltd","FearNaught","Fernanda Rizzo","Ferrgood Studio","Few and Far","Fighting Talk Communications","Fiona Watkins Design Limited","Fixperts at Forth","Foundation","Founded Design Ltd","Fourfeet Design","Francesca Cook Design Ltd",
                "Francis Rowland", "Frankie Thelwell", "FranklinTill", "Future Island-Island at Ulster University-led consortium", "Future Selves", "Futurice Ltd", "Fynn", "G R Moore Limited", "G3 Creative", "Gareth Neal Ltd", "Gareth Wild", "Garlic Agency", "Genevieve Bennett Ltd", "Genuinely Conscious", "George Charnley", "George Rowland", "GET LOST", "Gianfranco Fagotto", "Gitta Gschwendtner Ltd", "Giulia Villa", "Glen Cutwerk", "Glimpse", "Good Design Works", "Good Stuff Creative", "Good Will Studios", "Goodtale", "Goodwin Hartshorn", "Graduate Studies at College for Creative Studies", "Graft Creative", "Green Mat Workshop", "Green Orbit Digital", "Green Rooms landscapes & gardens", "GreenHeights", "H&A", "Hamish Duncan", "Hamish Makgill", "Han Li", "Hannah Pinnock", "Harriet Beesley", "Harrison Brands Ltd", "Haughton Design", "Helen Simmons", "Hey Low", "Hippo Digital", "Hive IT", "Hiyield", "Holmes Studio", "honours", "HOUSE OF HACKNEY", "Hundred Studio", "ICE", "ilka design limited", "Imagination Factory", "Inspirwood", "INTRA DRIVE LTD", "Irina Teti", "Isabella", "Jackie Malcolm", "Jake Owen", "James Kindred", "James Tooze", "Jamie Pinkham", "jan lewis creative", "Jane Penty", "Jason Bruges Studio", "Jason Mesut", "Jemima Duncalf", "Jess Baxter", "Jess Francis", "JK Creative Company", "Jo Mansfield", "Joanna boehnert", "John Gilbert", "Joseph Folkes", "Josh Elgood", "Joshua Tunstill", "Jude Pullen", "Juice by Design", "Justine Wyness", "Kaelum van der Berg", "Kai Davis", "Kaleido Grafik", "Kaleido Grafik", "Kanika Kalra", "Karishma Kusurkar", "Kathryn Summers", "Kavya Narayanan"
            ].map((word, index) => (
                <span key={index} className={styles.wordItem}>{word}</span>
            ))}
        </div>

    </section>
  )
}

export default Signature
